Atalov S. DevCIT

In [ ]:
# импортируйте библиотеку


#### 1. Создайте матрицу 3x3 с значениями от 2 до 10.

```
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]
```

#### 2. Создайте вектор с 10 нулями. Замените 6-ой элемент числом 11.
```
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]
```

#### 3. Создайте вектор с 10 элементами. Заполните четными числами начиная с 2.


#### 4. Оставьте в данном векторе только нули.
```
Данный вектор:
[1, 0, 2, 3, 4, 0, 6, 7, 0]
После:
[0, 0, 0]
```

#### 5. Создайте матрицу без прямого ввода вручную всей матрицы.

```
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
 ```

#### 6. Создайте матрицу 10 на 10, заполнив случайными числами.



#### 7. Создайте данную матрицу без прямого ввода.

```
[[5, 5, 5, 5, 5],
 [5, 5, 5, 5, 5],
 [5, 5, 5, 5, 5]]
```



#### 8. Сложите два вектора поэлементно и вычислите квадрат каждого элемента.

```
arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

Результат

[[ 400 1521 1089]
 [ 625  625  784]]
```


#### 9. Дана матрица. Найдите среднее значение каждой строки.
```
[[ 400, 1521, 1089]
 [ 625,  625,  784]]
```